---
title: "Proyecto Beetles"
author: Mariona Pajares y Estefanía Tobajas
output:
  pdf_document: default
  html_document: default
date: '2022-09-21'
---
los datos de origen presenta 4 años de estudio (desde 2008 a 2011) donde se registra la abundancia de 150 especies distintas 

calculamos la riqueza de especies de escarabajos para cada sitio y año
```{r,echo=FALSE, warning=FALSE,message=FALSE}
library(tidyverse)
library(tidyverse)
library(here) 
library(tidylog) 
library(summarytools) 
library(knitr)
library(performance)
library(effects)
library(kableExtra)


rawdata <- read.csv("datos/rawdata_bet.csv")
rawdata$YEAR<-as.factor(rawdata$YEAR)

bet_sum<-rawdata %>%
  group_by(PLOT, YEAR) %>%
  summarise(n_species = n(),ABUNDANCE = sum(ABUNDANCE))%>%
  rename(plot=PLOT, year=YEAR, abundance= ABUNDANCE)

bet_sum %>% 
    kable("latex",booktabs = TRUE, digits =  4,longtable = T,linesep = "")%>%
  kable_styling(font_size = 8,full_width = F, position="left")
```

#Import data
```{r}
rawdata <- read.csv("datos/rawdata_bet.csv")
```

#Clean data
```{r}
#remove nonsense variables
rawdata$BIOMASS <- NULL
rawdata$DAY <- NULL
rawdata$MONTH <- NULL
rawdata$LATITUDE <- NULL
rawdata$LONGITUDE <- NULL
rawdata$SAMPLE_DESC <- NULL
rawdata$YEAR <- as.factor(rawdata$YEAR)
rawdata$PLOT <- as.factor(rawdata$PLOT)

#please stop with the capital letters 
clean_data <- rawdata  %>% rename(plot = PLOT, year = YEAR, abundance = ABUNDANCE, genus_species = GENUS_SPECIES)

rm(rawdata)
```

#Plot data
```{r}
clean_data %>% 
  group_by(plot, genus_species) %>% summarise(n_species = n()) %>%
  ggplot(aes(x = plot, y = n_species, color = plot, fill = plot)) +
  geom_boxplot(alpha = .5) + 
  geom_jitter(alpha = .5) +
  theme_light() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 30, hjust = 1)) +
  labs(y = "No. of species", x = "Plot")
```


